export type RuleTemplate = {
  category: "Media" | "File types" | "Date and sequence" | "Sites and URLs" | "Save context";
  name: string;
  description: string;
  example: string;
  rule: string;
};

export const RULE_TEMPLATES: RuleTemplate[] = [
  {
    category: "Media",
    name: "Images into per-site folders",
    description: "Sorts every saved image by the site it came from",
    example: "Example: images/example.com/photo.jpg",
    rule: "mediatype: image\ninto: images/:pagedomain:/:filename:",
  },
  {
    category: "Media",
    name: "Videos into per-site folders",
    description: "Sorts every saved video by the site it came from",
    example: "Example: videos/example.com/clip.mp4",
    rule: "mediatype: video\ninto: videos/:pagedomain:/:filename:",
  },
  {
    category: "Media",
    name: "Audio into per-site folders",
    description: "Groups saved audio by the page where it was found",
    example: "Example: audio/example.com/podcast.mp3",
    rule: "mediatype: audio\ninto: audio/:pagedomain:/:filename:",
  },
  {
    category: "Media",
    name: "Screenshots by month",
    description: "Keeps filenames beginning with screenshot in dated folders",
    example: "Example: screenshots/2026/07/Screenshot 42.png",
    rule: "filename/i: ^screen([ _-]?shot|capture)\ninto: screenshots/:year:/:month:/:filename:",
  },
  {
    category: "File types",
    name: "PDFs into a documents folder",
    description: "Collects every PDF in one place",
    example: "Example: documents/report.pdf",
    rule: "fileext: pdf\ninto: documents/:filename:",
  },
  {
    category: "File types",
    name: "Archives into one folder",
    description: "Collects zip, rar, 7z, tar, and compressed archives",
    example: "Example: archives/project.zip",
    rule: "fileext/i: (zip|rar|7z|tar|gz|tgz|bz2|xz)\ninto: archives/:filename:",
  },
  {
    category: "File types",
    name: "Documents into one folder",
    description: "Collects common office and text documents",
    example: "Example: documents/notes.docx",
    rule: "fileext/i: (pdf|docx?|xlsx?|pptx?|odt|ods|rtf|txt|csv)\ninto: documents/:filename:",
  },
  {
    category: "File types",
    name: "E-books and comics",
    description: "Collects common e-book and digital comic formats",
    example: "Example: books/novel.epub",
    rule: "fileext/i: (epub|mobi|azw3?|pdf|cbz|cbr)\ninto: books/:filename:",
  },
  {
    category: "File types",
    name: "Apps and installers",
    description: "Keeps desktop and mobile installation packages together",
    example: "Example: installers/setup.msi",
    rule: "fileext/i: (exe|msi|dmg|pkg|deb|rpm|appimage|apk)\ninto: installers/:filename:",
  },
  {
    category: "File types",
    name: "Fonts into one folder",
    description: "Collects desktop and web font files",
    example: "Example: fonts/inter.woff2",
    rule: "fileext/i: (ttf|otf|woff2?|eot)\ninto: fonts/:filename:",
  },
  {
    category: "File types",
    name: "One folder per file extension",
    description: "Captures the extension and uses it as a folder name",
    example: "Example: files/png/screenshot.png",
    rule: "fileext: (.+)\ncapture: fileext\ninto: files/:$1:/:filename:",
  },
  {
    category: "Date and sequence",
    name: "Date-stamp every download",
    description: "Prefixes the original filename with the save date",
    example: "Example: 2026-07-12-report.pdf",
    rule: "sourceurl: .*\ninto: :date:-:filename:",
  },
  {
    category: "Date and sequence",
    name: "Daily inbox",
    description: "Creates one folder for each calendar day",
    example: "Example: inbox/2026/07/12/report.pdf",
    rule: "sourceurl: .*\ninto: inbox/:year:/:month:/:day:/:filename:",
  },
  {
    category: "Date and sequence",
    name: "Downloads by month",
    description: "Creates year and month folders while keeping the original filename",
    example: "Example: archive/2026/07/report.pdf",
    rule: "sourceurl: .*\ninto: archive/:year:/:month:/:filename:",
  },
  {
    category: "Date and sequence",
    name: "Weekly inbox",
    description: "Creates one inbox folder for each ISO week",
    example: "Example: inbox/2026-w28/report.pdf",
    rule: "sourceurl: .*\ninto: inbox/:year:-w:isoweek:/:filename:",
  },
  {
    category: "Date and sequence",
    name: "Sequential archive",
    description: "Prefixes files with Save In's persistent download counter",
    example: "Example: archive/42-report.pdf",
    rule: "sourceurl: .*\ninto: archive/:counter:-:filename:",
  },
  {
    category: "Sites and URLs",
    name: "One site, one folder",
    description: "Routes one chosen website into its own folder",
    example: "Example: example/an-interesting-page/report.pdf",
    rule: "pagedomain: example\\.com\ninto: example/:pagetitleslug:/:filename:",
  },
  {
    category: "Sites and URLs",
    name: "One folder per source site",
    description: "Groups downloads by the hostname serving the file",
    example: "Example: sites/cdn.example.com/photo.jpg",
    rule: "sourceurl: .*\ninto: sites/:sourcedomain:/:filename:",
  },
  {
    category: "Sites and URLs",
    name: "One folder per page site",
    description: "Groups files by the website you were browsing rather than the file host",
    example: "Example: sites/example.com/photo.jpg",
    rule: "pageurl: .*\ninto: sites/:pagedomain:/:filename:",
  },
  {
    category: "Sites and URLs",
    name: "Page-title prefix",
    description: "Adds a filesystem-safe page title before the original filename",
    example: "Example: pages/an-interesting-page-report.pdf",
    rule: "sourceurl: .*\ninto: pages/:pagetitleslug:-:filename:",
  },
  {
    category: "Sites and URLs",
    name: "Capture part of the URL",
    description: "Uses a regex capture group in the saved filename",
    example: "Example: imgur/abc123-photo.jpg",
    rule: "sourceurl: imgur\\.com/(\\w+)\ncapture: sourceurl\ninto: imgur/:$1:-:filename:",
  },
  {
    category: "Save context",
    name: "Browser downloads inbox",
    description: "Keeps tracked browser-owned downloads in a separate folder",
    example: "Example: browser-downloads/archive.zip",
    rule: "context: browser\ninto: browser-downloads/:filename:",
  },
  {
    category: "Save context",
    name: "Link downloads inbox",
    description: "Separates files saved from links from embedded media",
    example: "Example: links/report.pdf",
    rule: "context: link\ninto: links/:filename:",
  },
  {
    category: "Save context",
    name: "Selected text inbox",
    description: "Keeps files created from selected page text together",
    example: "Example: selections/2026-07-12-selection.txt",
    rule: "context: selection\ninto: selections/:date:-:filename:",
  },
  {
    category: "Save context",
    name: "Tab saves inbox",
    description: "Keeps files saved from tab actions together",
    example: "Example: tabs/page.html",
    rule: "context: tab\ninto: tabs/:filename:",
  },
];
