import { CONFLICT_ACTION, SHORTCUT_TYPES } from "../shared/constants.ts";
import { CONTENT_OPTION_DEFAULTS } from "./content-options.ts";

export const LEGACY_REFERER_HEADER_FILTER = "*://i.pximg.net/*";

// Keep raw defaults in a dependency-leaf module. The live options bag needs
// them synchronously, while the full schema depends on routing validators that
// already read that bag.
export const OPTION_DEFAULTS = {
  ...CONTENT_OPTION_DEFAULTS,
  conflictAction: CONFLICT_ACTION.UNIQUIFY,
  debug: false,
  enableLastLocation: true,
  recentDestinationCount: 1,
  enableNumberedItems: true,
  filenamePatterns: "",
  keyLastUsed: "e",
  keyRoot: "e",
  preferLinks: false,
  preferLinksFilterEnabled: false,
  preferLinksFilter: ".*commons.wikimedia.org/wiki/File:.*",
  notifyDuration: 7000,
  notifyOnFailure: true,
  notifyOnRuleMatch: true,
  notifyOnSuccess: true,
  notifyOnLinkPreferred: true,
  promptAssistantEnabled: false,
  page: true,
  paths: ". // (alias: Downloads)\nImages\nVideos\nAudio\nDocuments",
  prompt: false,
  promptIfNoExtension: false,
  promptOnFailure: true,
  promptOnShift: true,
  replacementChar: "_",
  routeExclusive: false,
  routeFailurePrompt: false,
  routeHideFolderChoices: false,
  routeSkipUnmatched: false,
  selection: true,
  shortcutLink: false,
  shortcutMedia: false,
  shortcutPage: false,
  shortcutTab: false,
  shortcutType: SHORTCUT_TYPES.HTML_REDIRECT,
  saveSourceSidecar: false,
  truncateLength: 240,
  appendMimeExtension: true,
  fetchViaFetch: false,
  fallbackFetch: true,
  includeFetchCredentials: true,
  externalDownloadAllowlist: "",
  webhookEnabled: false,
  webhookUrl: "",
  webhookIncludePageUrl: false,
  webhookIncludePageTitle: false,
  webhookIncludeSelectionText: false,
  trackBrowserDownloads: false,
  routeBrowserDownloads: false,
  browserDownloadFiltersEnabled: false,
  browserDownloadFilter: "",
  browserDownloadExcludeFilter: "",
  routeBrowserDownloadsFirefox: false,
  tabEnabled: false,
  closeTabOnSave: false,
  setRefererHeader: false,
  setRefererHeaderFilter: `${LEGACY_REFERER_HEADER_FILTER}\n*://*.mangadex.network/*`,
} as const;

export const defaultOptions = () => ({ ...OPTION_DEFAULTS });
