name: Checks

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: yarn
      - run: yarn build
      - run: yarn lint
      - run: yarn test

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: yarn
      - run: HEADLESS=1 yarn e2e:chrome
      - run: HEADLESS=1 yarn e2e:firefox
